### ISSUE TITLE
Is Telnet  working

### ISSUE THREAD

**Issue by MichaelB2018** [sbozarth/homebridge-lc7001#2]
Great work! Just one question. As I'm playing with this, I'm wondering if I can issue commands straight from Telnet. It this works, I may be tempted to build a Python integration to MQTT for integration in Home Assistant. But one step at the time.. so would love to be able to send commands via telnet. I'm using this command:

{"ID":1,"Service":"ListZones"}

but nothing comes back. Any idea?

**Comment by MichaelB2018** [comment]
Never mind... The problem was the trailing 0x00. So I wrote a small python program and now it's working that way. Therefore I have a baseline to work from now

**Comment by ronluna** [comment]
> Never mind... The problem was the trailing 0x00. So I wrote a small python program and now it's working that way. Therefore I have a baseline to work from now

I'm trying the following:
`{"ID":1,"Service":"ListZones"}\n\r\n\0`

But nothing comes back. How were you able to successfully submit a request via telnet with python?

**Comment by MichaelB2018** [comment]
Not using Telnet via Python, just native Python sockets:
```
    s = socket.socket()
    s.connect('LCM1.local', 2122)
    msg_send = json.dumps(cmd)+chr(0)
    s.send(msg_send.encode())
```

My code is made to interact with Home Assistant via MQTT. If you are looking to do the same I could share. It's just not fully reconnecting yet in some funky partial restart scenarios... so not totally ready for prime time.

**Comment by ronluna** [comment]
I’m trying to ported to lua . Have not been able to get a reply back from the controller using socket 

And official documentation ... nowhere to be found...

**Comment by ronluna** [comment]
Working now, there was an error on the request I was sending.

**Comment by MichaelB2018** [comment]
How did you get it done? Would love to learn as well :)

**Comment by ronluna** [comment]
This is a little test example in lua for sending and receiving to LC7001 gateway. 

`
local cmd = "{\"ID\":1,\"Service\":\"SystemInfo\"}"

local socket = require("socket")
local tcp = assert(socket.tcp())

tcp:connect("ip_address", 2112)
tcp:settimeout(5)
tcp:send(cmd .. "\0")

  local buffer = {}
  local message, err, incoming
  repeat
    incoming, err = tcp: receive (1)
    local delimiter = (incoming == "\0")
    if not delimiter then 
    	buffer[#buffer+1] = incoming 
    end
  until err or delimiter
	if not err then 
  		message = table.concat (buffer) 
	end
tcp:close()

print(message)
`
