### ISSUE TITLE
Unhandled Service: EliotErrors

### ISSUE THREAD

**Issue by ghost** [sbozarth/homebridge-lc7001#3]
Following the transition from Samsung ARTIK Cloud to Legrand Cloud, I started receiving errors on my Homebridge R-Pi console (running Homebridge interactively).

The homebridge-lc7001 seems to start normally, however I then start seeing "[LC7001] Unhandled service: EliotErrors" about every 30 seconds.

During this time, I can still work with the LC7001, through HomeKit and HomeBridge, however it seems to eventually become unstable and stop functioning all together, after about 24 hours.

My Legrand 7001 Whole House controller in now running Version 4.0.0-269-gb397

**Comment by sbozarth** [comment]
If you are comfortable modifying the code, in lib/lc7001.js, find the following line:

this.log('Unhandled service: ' + response.Service);

Add on the line immediately after it:

this.log(response);

This will cause the plugin to dump the offending JSON object into the log after the error message. Please copy and past a few of the JSON objects that generate this error.

**Comment by ghost** [comment]
Sure thing, other than the time changing, all the EliotErrors seem to be the same, here is a couple of them:
[9/5/2019, 7:05:32 PM] [LC7001] Unhandled service: EliotErrors
[9/5/2019, 7:05:32 PM] [LC7001] { Service: 'EliotErrors',
  CurrentTime: 1567710332,
  EliotConnect: 4,
  Connect: 1,
  DNS: 3,
  UserToken: 1 }
[9/5/2019, 7:06:00 PM] [LC7001] Unhandled service: EliotErrors
[9/5/2019, 7:06:00 PM] [LC7001] { Service: 'EliotErrors',
  CurrentTime: 1567710360,
  EliotConnect: 4,
  Connect: 1,
  DNS: 3,
  UserToken: 1 }
[9/5/2019, 7:08:21 PM] [LC7001] Unhandled service: EliotErrors
[9/5/2019, 7:08:21 PM] [LC7001] { Service: 'EliotErrors',
  CurrentTime: 1567710501,
  EliotConnect: 4,
  Connect: 1,
  DNS: 3,
  UserToken: 1 }

**Comment by sbozarth** [comment]
Added handler for Service=='EliotErrors' in 0.6.0. Strangely, these packets do not have an ID property. Logic that previously declared ID=0 as LC7001-initiated now tests ID=0 OR ID undefined.

**Comment by ghost** [comment]
Yeah, I noticed that as well. installed 0.61 and I new see "EliotErrors ignored." Thanks!
