### ISSUE TITLE
Unknown LC7001 initiated object!

### ISSUE THREAD

**Issue by ghost** [sbozarth/homebridge-lc7001#4]
Similar to the Unhandled Service: EliotErrors, after upgrading to firmware version 4.0.1-28 today, I am now starting to see the exceptions "Unknown LC7001 initiated object!".

Quick scan of the js file and I can see that the default "else" clause is this error, or the EliotErrors.

Again, still working, but Legrand must have implemented something new in their firmware.

**Comment by sbozarth** [comment]
Immediately following the "Unknown LC7001 initiated object!" message should be the JSON object received beginning "{ID:0". Please copy and past the unknown JSON object so a handler can be built for it, even if it is just to ignore it.

**Comment by ghost** [comment]
Here ya go...

[9/5/2019, 7:10:13 PM] [LC7001] Unknown LC7001 initiated object!
[9/5/2019, 7:10:13 PM] [LC7001] { ID: 0,
  Context: '006916Debug : Connection Log',
  DebugStr: 'Initializing',
  CurrentTime: 1567728613,
  uSec: 161,
  Seqno: 9581,
  Number: 0 }
[9/5/2019, 7:10:13 PM] [LC7001] Unknown LC7001 initiated object!
[9/5/2019, 7:10:13 PM] [LC7001] { ID: 0,
  Context: '006917Debug : Connection Log',
  DebugStr: 'Getting IP Address.',
  CurrentTime: 1567728613,
  uSec: 3159,
  Seqno: 9582,
  Number: 1 }
[9/5/2019, 7:10:14 PM] [LC7001] Unknown LC7001 initiated object!
[9/5/2019, 7:10:14 PM] [LC7001] { ID: 0,
  Context: '006918Debug : Connection Log',
  DebugStr: 'Address Successfully Resolved.',
  CurrentTime: 1567728614,
  uSec: 2054,
  Seqno: 9583,
  Number: 2 }
[9/5/2019, 7:10:14 PM] [LC7001] Unknown LC7001 initiated object!
[9/5/2019, 7:10:14 PM] [LC7001] { ID: 0,
  Context: '006919Debug : Connection Log',
  DebugStr: 'Connecting Socket.',
  CurrentTime: 1567728614,
  uSec: 315,
  Seqno: 9584,
  Number: 3 }
[9/5/2019, 7:10:14 PM] [LC7001] Unknown LC7001 initiated object!
[9/5/2019, 7:10:14 PM] [LC7001] { ID: 0,
  Context: '006920Debug : Connection Log',
  DebugStr: 'Connecting SSL',
  CurrentTime: 1567728614,
  uSec: 2720,
  Seqno: 9585,
  Number: 4 }
[9/5/2019, 7:10:15 PM] [LC7001] Unknown LC7001 initiated object!
[9/5/2019, 7:10:15 PM] [LC7001] { ID: 0,
  Context: '006921Debug : Connection Log',
  DebugStr: 'SSL Connected!',
  CurrentTime: 1567728615,
  uSec: 1149,
  Seqno: 9586,
  Number: 5 }

**Comment by sbozarth** [comment]
Debug message handling was actually added in 0.4.1, but mistakenly placed inside the logic that tests for Service being defined. Moved the handler outside this logic in 0.6.0. This does mean that the Debug handler was not ever really being tested.
